### ISSUE TITLE
Mettre en évidence le caractère modifiable d'une candidature envoyée

### ISSUE THREAD

**Issue by HelaG** [sgmap/etudiant-entrepreneur#9]
* Solution simple : le préciser dans le mail de confirmation envoyé après dépôt de la candidature 
* Solution _premium_ : modifier le dernier CTA quand on arrive sur l'application à partir d'un lien personnalisé 
A discuter en planif
cf mail utilisateur du 06/12 à 1:13AM.

**Comment by nbrohee** [comment]
Solved with https://github.com/sgmap/etudiant-entrepreneur/commit/11c4856f42eb99188e51e298b20b0b34e7879027
